on:
  push:
jobs:
   build: 
     runs-on: ubuntu-latest
     steps: 
      - uses: actions/checkout@v2
        with: 
          fetch-depth: 0
      - name: get file changes
        run: | 
          git diff --name-only ${{ github.event.before }} ${{ github.event.after }}
      - name: get changes
        id: test
        run: | 
          git diff HEAD~1
      - name: get variable output
        run: |
          echo ${{ steps.test.outputs.stdout }}
