on:
  push:
jobs:
   build: 
     runs-on: ubuntu-latest
     defaults: 
      run:
        shell: bash -l {0}
     steps: 
      - uses: actions/checkout@v2
        with: 
          fetch-depth: 0
      - name: get file changes
        run: | 
          git diff --name-only ${{ github.event.before }} ${{ github.event.after }}
      - name: get changes
        id: test
        run: |
          test123=$( git diff HEAD~1)
          echo ::set-output name=test1::$(git diff HEAD~1)
          echo "::set-output name=test123::$test123"
          echo "Testing123=$('git diff HEAD~1')" >> $GITHUB_ENV
          
          
      - name: get variable output
      
        run: |
          echo ${{ steps.test.outputs.test1 }}
          echo ${{ steps.test.output.test123 }}


