on:
  push:
env:
  DEVOPS_DIR: devops
jobs:
   build: 
     runs-on: ubuntu-latest
     steps: 
      - uses: actions/checkout@v2
        with: 
          fetch-depth: 0
      - name: get file changes
        run: | 
          git diff --name-only ${{ github.event.before }} ${{ github.event.after }}
      - name: get changes
        run: |
          DIFF=$( git diff HEAD~1) || true
          echo ::set-output name=test1::$DIFF
        id: test11
      - name: get variable output
        run: |
          echo "the String is : ${{ steps.test11.outputs.test1 }}"
      - name: test condition
        if: contains('a', ${{ steps.test11.outputs.test1 }})
        run: |
          echo "Lets run"
          
      - name: Check-out devops repository
        uses: actions/checkout@v2
        with:
          repository: craigjanzen/pythontest

      - name: Hello World
        run: python ${{ env.DEVOPS_DIR }}/hello_world.py
        shell: sh


